name: Publish Docker Image

on:
  push:
    branches: ["master"]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  docker:
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        git-version: ["2.44.0"]
    runs-on: ${{ matrix.arch }}

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Get the commit hash
      - uses: prompt/actions-commit-hash@v3

      # Login to Docker Hub
      - name: Login to Repo
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: fascinated/paste:latest

      - name: Build Docker Image (Tagged)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: fascinated/paste:${{ steps.commit.outputs.short }}
