version: "3.9"
services:
  paste:
    # build:
    #   context: ../
    #   dockerfile: Dockerfile
    image: fascinated/paste:latest
    restart: always
    environment:
      - PASTE_ID_LENGTH=12
      - MAX_PASTE_SIZE=5000000
      - MONGO_URI=mongodb://root:root@mongo:27017
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  mongo:
    image: "bitnami/mongodb:latest"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=10.0.0.86 # SET THIS TO THE MACHINES IP
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=supersupersecretpassword
      - MONGODB_USERNAME=paste
      - MONGODB_PASSWORD=paste
      - MONGODB_DATABASE=paste
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/bitnami/mongodb
