{
 "title": "Paste",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Allocated (In Use)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Goroutunes" }
   ]
  },
  {
   "title": "Goroutunes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Goroutunes" }
   ]
  },
  { "title": "Paste Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Pastes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "total_pastes", "legendFormat": "Total Pastes" }
   ]
  },
  {
   "title": "Average Paste Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "avg_paste_size", "legendFormat": "Avg Size" }
   ]
  },
  {
   "title": "Requests (Per 5 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(paste_requests_total{method=\"GET\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (method) (rate(paste_requests_total{method=\"POST\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}